// Code generated by protoc-gen-go. DO NOT EDIT.
// source: greet.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GreetRequest struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetRequest) Reset()         { *m = GreetRequest{} }
func (m *GreetRequest) String() string { return proto.CompactTextString(m) }
func (*GreetRequest) ProtoMessage()    {}
func (*GreetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_32c0044392f32579, []int{0}
}

func (m *GreetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetRequest.Unmarshal(m, b)
}
func (m *GreetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetRequest.Marshal(b, m, deterministic)
}
func (m *GreetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetRequest.Merge(m, src)
}
func (m *GreetRequest) XXX_Size() int {
	return xxx_messageInfo_GreetRequest.Size(m)
}
func (m *GreetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GreetRequest proto.InternalMessageInfo

func (m *GreetRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

type GreetResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetResponse) Reset()         { *m = GreetResponse{} }
func (m *GreetResponse) String() string { return proto.CompactTextString(m) }
func (*GreetResponse) ProtoMessage()    {}
func (*GreetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_32c0044392f32579, []int{1}
}

func (m *GreetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetResponse.Unmarshal(m, b)
}
func (m *GreetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetResponse.Marshal(b, m, deterministic)
}
func (m *GreetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetResponse.Merge(m, src)
}
func (m *GreetResponse) XXX_Size() int {
	return xxx_messageInfo_GreetResponse.Size(m)
}
func (m *GreetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GreetResponse proto.InternalMessageInfo

func (m *GreetResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type CalculatorRequest struct {
	Number1              int64    `protobuf:"varint,1,opt,name=Number1,proto3" json:"Number1,omitempty"`
	Number2              int64    `protobuf:"varint,2,opt,name=Number2,proto3" json:"Number2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CalculatorRequest) Reset()         { *m = CalculatorRequest{} }
func (m *CalculatorRequest) String() string { return proto.CompactTextString(m) }
func (*CalculatorRequest) ProtoMessage()    {}
func (*CalculatorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_32c0044392f32579, []int{2}
}

func (m *CalculatorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalculatorRequest.Unmarshal(m, b)
}
func (m *CalculatorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalculatorRequest.Marshal(b, m, deterministic)
}
func (m *CalculatorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalculatorRequest.Merge(m, src)
}
func (m *CalculatorRequest) XXX_Size() int {
	return xxx_messageInfo_CalculatorRequest.Size(m)
}
func (m *CalculatorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CalculatorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CalculatorRequest proto.InternalMessageInfo

func (m *CalculatorRequest) GetNumber1() int64 {
	if m != nil {
		return m.Number1
	}
	return 0
}

func (m *CalculatorRequest) GetNumber2() int64 {
	if m != nil {
		return m.Number2
	}
	return 0
}

type CalculatorResponse struct {
	Result               int64    `protobuf:"varint,1,opt,name=Result,proto3" json:"Result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CalculatorResponse) Reset()         { *m = CalculatorResponse{} }
func (m *CalculatorResponse) String() string { return proto.CompactTextString(m) }
func (*CalculatorResponse) ProtoMessage()    {}
func (*CalculatorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_32c0044392f32579, []int{3}
}

func (m *CalculatorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalculatorResponse.Unmarshal(m, b)
}
func (m *CalculatorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalculatorResponse.Marshal(b, m, deterministic)
}
func (m *CalculatorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalculatorResponse.Merge(m, src)
}
func (m *CalculatorResponse) XXX_Size() int {
	return xxx_messageInfo_CalculatorResponse.Size(m)
}
func (m *CalculatorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CalculatorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CalculatorResponse proto.InternalMessageInfo

func (m *CalculatorResponse) GetResult() int64 {
	if m != nil {
		return m.Result
	}
	return 0
}

type PrimeRequest struct {
	Number1              int64    `protobuf:"varint,1,opt,name=Number1,proto3" json:"Number1,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrimeRequest) Reset()         { *m = PrimeRequest{} }
func (m *PrimeRequest) String() string { return proto.CompactTextString(m) }
func (*PrimeRequest) ProtoMessage()    {}
func (*PrimeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_32c0044392f32579, []int{4}
}

func (m *PrimeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimeRequest.Unmarshal(m, b)
}
func (m *PrimeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimeRequest.Marshal(b, m, deterministic)
}
func (m *PrimeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimeRequest.Merge(m, src)
}
func (m *PrimeRequest) XXX_Size() int {
	return xxx_messageInfo_PrimeRequest.Size(m)
}
func (m *PrimeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PrimeRequest proto.InternalMessageInfo

func (m *PrimeRequest) GetNumber1() int64 {
	if m != nil {
		return m.Number1
	}
	return 0
}

type PrimeResponse struct {
	Result               int64    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrimeResponse) Reset()         { *m = PrimeResponse{} }
func (m *PrimeResponse) String() string { return proto.CompactTextString(m) }
func (*PrimeResponse) ProtoMessage()    {}
func (*PrimeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_32c0044392f32579, []int{5}
}

func (m *PrimeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimeResponse.Unmarshal(m, b)
}
func (m *PrimeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimeResponse.Marshal(b, m, deterministic)
}
func (m *PrimeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimeResponse.Merge(m, src)
}
func (m *PrimeResponse) XXX_Size() int {
	return xxx_messageInfo_PrimeResponse.Size(m)
}
func (m *PrimeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PrimeResponse proto.InternalMessageInfo

func (m *PrimeResponse) GetResult() int64 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*GreetRequest)(nil), "greet.GreetRequest")
	proto.RegisterType((*GreetResponse)(nil), "greet.GreetResponse")
	proto.RegisterType((*CalculatorRequest)(nil), "greet.CalculatorRequest")
	proto.RegisterType((*CalculatorResponse)(nil), "greet.CalculatorResponse")
	proto.RegisterType((*PrimeRequest)(nil), "greet.PrimeRequest")
	proto.RegisterType((*PrimeResponse)(nil), "greet.PrimeResponse")
}

func init() {
	proto.RegisterFile("greet.proto", fileDescriptor_32c0044392f32579)
}

var fileDescriptor_32c0044392f32579 = []byte{
	// 336 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x59, 0x43, 0x23, 0x1d, 0xeb, 0xc1, 0xb1, 0x4a, 0x2c, 0x08, 0x92, 0x8b, 0x39, 0x68,
	0x5b, 0x23, 0x82, 0x17, 0x05, 0xad, 0xd2, 0x8b, 0x14, 0x49, 0x6f, 0x5e, 0x64, 0x5b, 0xc6, 0x10,
	0x4c, 0xb2, 0x75, 0x77, 0x53, 0xe8, 0x8f, 0xf3, 0xbf, 0x49, 0xb7, 0x9b, 0x36, 0xc5, 0x82, 0xf6,
	0xd4, 0xbe, 0x9d, 0x97, 0xf7, 0x76, 0x3e, 0x16, 0xf6, 0x62, 0x49, 0xa4, 0xdb, 0x13, 0x29, 0xb4,
	0xc0, 0x9a, 0x11, 0xfe, 0x25, 0x34, 0xfa, 0xf3, 0x3f, 0x11, 0x7d, 0x15, 0xa4, 0x34, 0x9e, 0x02,
	0x7c, 0x24, 0x52, 0xe9, 0xf7, 0x9c, 0x67, 0xe4, 0xb1, 0x33, 0x16, 0xd4, 0xa3, 0xba, 0x39, 0x19,
	0xf0, 0x8c, 0xfc, 0x73, 0xd8, 0xb7, 0x76, 0x35, 0x11, 0xb9, 0x22, 0x3c, 0x06, 0x57, 0x92, 0x2a,
	0x52, 0x6d, 0xbd, 0x56, 0xf9, 0x7d, 0x38, 0xe8, 0xf1, 0x74, 0x5c, 0xa4, 0x5c, 0x0b, 0x59, 0x86,
	0x7b, 0xb0, 0x3b, 0x28, 0xb2, 0x11, 0xc9, 0x2b, 0xe3, 0x76, 0xa2, 0x52, 0xae, 0x26, 0xa1, 0xb7,
	0x53, 0x9d, 0x84, 0xfe, 0x05, 0x60, 0x35, 0x68, 0x55, 0x1b, 0xad, 0x6a, 0x9d, 0xc8, 0x2a, 0x3f,
	0x80, 0xc6, 0xab, 0x4c, 0x32, 0xfa, 0xb3, 0x71, 0xbe, 0x89, 0x75, 0x6e, 0xdc, 0xc4, 0x29, 0x37,
	0x09, 0xbf, 0x1d, 0x8b, 0x68, 0x48, 0x72, 0x9a, 0x8c, 0x09, 0x43, 0xa8, 0x19, 0x8d, 0x87, 0xed,
	0x05, 0xd0, 0x2a, 0xc0, 0x56, 0x73, 0xfd, 0xd0, 0x86, 0xdf, 0x81, 0x3b, 0x2c, 0xb2, 0x68, 0x32,
	0x46, 0xcf, 0xce, 0x7f, 0xd1, 0x69, 0x9d, 0x6c, 0x98, 0xd8, 0xcf, 0x7b, 0xd0, 0x5c, 0x5e, 0x81,
	0xe4, 0x50, 0x4b, 0xe2, 0x59, 0x92, 0xc7, 0x5b, 0xdc, 0xa0, 0xcb, 0xf0, 0x09, 0x8e, 0xca, 0x68,
	0x32, 0xab, 0x2f, 0x50, 0xa8, 0x65, 0x4a, 0x95, 0xdc, 0x32, 0x65, 0x0d, 0x52, 0x97, 0xe1, 0x2d,
	0xd4, 0x5f, 0x44, 0x1e, 0x6f, 0x4b, 0x20, 0x60, 0x78, 0x03, 0xee, 0xc3, 0x34, 0x9e, 0x33, 0xf8,
	0x7f, 0x61, 0xc0, 0xf0, 0xde, 0x3e, 0xb9, 0xe7, 0x29, 0xc9, 0x99, 0xc8, 0x69, 0xab, 0xd2, 0x2e,
	0x7b, 0x6c, 0xbe, 0xe1, 0x27, 0x4f, 0x67, 0x3c, 0xef, 0x18, 0x47, 0xc7, 0x3c, 0xff, 0x91, 0x6b,
	0x7e, 0xae, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xb0, 0xa6, 0xb6, 0x1c, 0x14, 0x03, 0x00, 0x00,
}
